services:
  fcp-sfd-messaging-gateway:
    build:
      target: development
    image: fcp-sfd-messaging-gateway-development
    container_name: fcp-sfd-messaging-gateway-test
    command: npm run test
    env_file:
      - path: .env
        required: false
    environment:
      PORT: 3003
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    volumes:
      - ./src/:/home/node/src
      - ./test/:/home/node/test
      - ./package.json:/home/node/package.json
      - ./coverage:/home/node/coverage
    networks:
      - cdp-tenant

  localstack:
    env_file:
      - path: .env
        required: false