services:
  fcp-sfd-comms:
    build:
      target: development
    image: fcp-sfd-comms-development
    container_name: fcp-sfd-comms-test
    command: npm run test
    env_file:
      - path: .env
        required: false
    environment:
      PORT: 3003
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    volumes:
      - ./coverage:/home/node/coverage
    networks:
      - cdp-tenant

  localstack:
    env_file:
      - path: .env
        required: false

  mongodb:
    volumes:
      - mongodb-data:/data

volumes:
  mongodb-data: